# MLflow Project Environment for House Prices CI Pipeline
# Author: Amirullah
# Python: 3.12

name: mlflow-house-prices-ci
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      # Core ML & MLflow
      - mlflow==2.11.3
      - scikit-learn==1.4.0
      - pandas==2.2.0
      - numpy==1.26.3
      - scipy==1.12.0

      # Utilities
      - joblib>=1.3.0

      # Visualization (for artifacts)
      - matplotlib>=3.8.0
      - seaborn>=0.13.0
